#!/bin/bash
sudo svc -d /service/camera
sleep 1
#exec env LD_LIBRARY_PATH=/usr/local/frc/lib java -jar java-multiCameraServer-all.jar
#exec ./runCamera
#exec ./multiCameraServer.py

for pid in $(ps -ef | grep "python3" | awk '{print $2}'); do kill -9 $pid; done
sleep 1
exec ./multiCameraServer.py